config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users, only: [:create]
  resources :sessions, only: [:create]

  resources :flights, only: [:index] do
    collection do
      get :search
      get "/:flight_id/booking/seats/:seats" => "bookings#book", as: :book
    end
  end

  resources :bookings, only: [:create, :index, :edit, :update, :destroy] do
    collection do
      get :manage
      get :search
      get "/:booking_id/checkout" => "bookings#checkout", as: :checkout
      get "/:booking_id/payment" => "bookings#payment", as: :payment
      get "/:booking_id/confirmation" => "bookings#confirmation",
          as: :confirmation
    end
  end

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :origin_airport, class_name: "Airport"
  belongs_to :destination_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  validates :flight_no, presence: true
  validates :airline, presence: true
  validates :origin_airport_id, presence: true
  validates :destination_airport_id, presence: true
  validates :departure_datetime, presence: true
  validates :arrival_datetime, presence: true
  validates :capacity, presence: true
  validates :available_seats, presence: true
  validates :price, presence: true

  scope(
    :not_departed,
    lambda do
      where("departure_datetime > ?", Time.now)
    end
  )

  scope(
    :coming_from,
    lambda do |id|
      where("origin_airport_id = ?", id) unless id == ""
    end
  )

  scope(
    :going_to,
    lambda do |id|
      where("destination_airport_id = ?", id) unless id == ""
    end
  )

  scope(
    :has_enough_seats,
    lambda do |seats|
      where("available_seats >= ?", seats) unless seats == 0
    end
  )

  scope(
    :takeoff_on,
    lambda do |date|
      where(
        "Date(departure_datetime) = ?", Date.parse(date).strftime("%Y-%m-%d")
      ) unless date == ""
    end
  )

  def self.get_match(params)
    coming_from(params[:origin_airport_id]).
      going_to(params[:destination_airport_id]).
      has_enough_seats(params[:available_seats].to_i).
      takeoff_on(params[:departure_datetime])
  end

  def decorate
    @decorate ||= FlightDecorator.new(self)
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @presenter = Flights::IndexPresenter.new(
      Flight.not_departed.paginate(page: params[:page], per_page: 30)
    )
  end

  def search
    @presenter = Flights::IndexPresenter.new(
      Flight.not_departed.get_match(flight_params)
    )
    @presenter.seats = flight_params[:available_seats]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def flight_params
    params.require(:flight).permit(
      :origin_airport_id,
      :destination_airport_id,
      :departure_datetime,
      :available_seats
    )
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<% unless @presenter.flights.blank? %>
  <table class="bordered">
    <thead>
      <tr>
        <th colspan="2">Airline</th>
        <th>From</th>
        <th>To</th>
        <th>Departure</th>
        <th>Arrival</th>
        <th>Book</th>
      </tr>
    </thead>
    <tbody>
      <% @presenter.flights.each do |flight| %>
        <tr>
          <td>Img</td>
          <td><%= flight.airline %></td>
          <td><%= flight.origin_airport.decorate.name_with_state %></td>
          <td><%= flight.destination_airport.decorate.name_with_state %></td>
          <td><%= flight.decorate.departure_d %> <br> <%= flight.decorate.departure_t %></td>
          <td><%= flight.decorate.arrival_d %> <br> <%= flight.decorate.arrival_t %></td>
          <td><%= link_to "book", book_flights_path(flight.id, @presenter.seats), class: "btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <span>No flight found for your search. You could search for a different day</span>
<% end %>

app/views/flights/index.html.erb
<div class="">
  <div class="container">
    <div class="">
      <h5>Flight Time Board</h5>
      <div id="flight-time-board">
        <%= render @presenter.flight %>
        <div class="digg-pagination paging">
          <%= will_paginate @presenter.flights %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flights/search.html.erb
<h1>Flights#search</h1>
<p>Find me in app/views/flights/search.html.erb</p>
<%= @result.inspect %>

app/views/flights/search.js.erb
container = $("#flight-time-board");
container.empty().append("<%= j render('flight') %>");