config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users, only: [:create]
  resources :sessions, only: [:create]

  resources :flights, only: [:index] do
    collection do
      get :search
      get "/:flight_id/booking/seats/:seats" => "bookings#book", as: :book
    end
  end

  resources :bookings, only: [:create, :index, :edit, :update, :destroy] do
    collection do
      get :manage
      get :search
      get "/:booking_id/checkout" => "bookings#checkout", as: :checkout
      get "/:booking_id/payment" => "bookings#payment", as: :payment
      get "/:booking_id/confirmation" => "bookings#confirmation",
          as: :confirmation
    end
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passengers
  belongs_to :user

  validates :flight_id, presence: true

  accepts_nested_attributes_for :passengers

  before_create :make_new

  def make_new
    self.paid = false
    self.booking_number = Random.rand(1_000_000_000..9_999_999_999).to_s
    self.amount = flight.price * passengers.size
  end

  def user_or_passenger
    if user.nil?
      passengers.first
    else
      user
    end
  end

  def remaining_seats
    flight.available_seats - passengers.size
  end

  def release_seats
    flight.available_seats += passengers.size
    flight.save
    destroy
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authorize, only: [:index]

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def book
    flight = Flight.find(params[:flight_id])
    @booking = Booking.new(flight_id: flight.id)
    params[:seats].to_i.times { @booking.passengers.build }
  end

  def create
    book = Booking.new(booking_params)
    book.user_id = current_user.id if current_user

    if book.save
      book.flight.update(available_seats: book.remaining_seats)
      redirect_to checkout_bookings_path(booking_id: book.id)
    else
      redirect_to :back, alert: "Sorry, your flight was not booked"
    end
  end

  def manage
  end

  def search
    @booking = Booking.find_by_booking_number(params[:booking_number])
    if @booking.blank?
      redirect_to :back, notice: "No booking with that Number was found."
    else
      redirect_to edit_booking_path(@booking.id)
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    render :book
  end

  def update
    booking = Booking.find(params[:id])
    booking.update(booking_params)
    ConfirmationMailer.thank_you(
      booking.id,
      "Updated Passengers' Information"
    ).deliver_now

    redirect_to :back, notice: "Booking updated successfully!"
  end

  def destroy
    booking = Booking.find(params[:id])
    booking.release_seats
    redirect_to :back, notice: "Booking canceled successfully!"
  end

  def checkout
    @booking = Booking.find(params[:booking_id])
  end

  def payment
    booking_id = params[:booking_id]

    Booking.find(booking_id).update(paid: true)
    ConfirmationMailer.thank_you(
      booking_id,
      "Thank You For Your Patronage"
    ).deliver_now

    redirect_to(
      confirmation_bookings_path(booking_id),
      notice: "Payment confirmed!"
    )
  end

  def confirmation
    @booking = Booking.find(params[:booking_id])
  end

  def booking_params
    params.require(:booking).permit(
      :flight_id,
      passengers_attributes: [:id, :passenger_id, :name, :email, :phone]
    )
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def paypal_url(booking, return_url)
    values = {
      business: "chigboemmanuel-facilitator@gmail.com",
      cmd: "_cart",
      upload: 1,
      return: return_url,
      invoice: booking.id + rand(100_000..999_999)
    }

    booking.passengers.each_with_index do |item, index|
      values.merge!(
        "amount_#{index + 1}" => booking.flight.price,
        "item_name_#{index + 1}" => item.name
      )
    end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/views/bookings/_content.html.erb
<div class="" id="passengers">
  <div>
    <h5><%= @booking.flight.airline %>
      <span class="flight-no">Flight NO: <%= @booking.flight.id %></span>
    </h5>
    
    <div class="row">
      <div class="col l5">
        <h5>FROM</h5>
        <div>
          <%= @booking.flight.origin_airport.decorate.name_with_state %> state
        </div>
        <div>
          <%= @booking.flight.decorate.departure_d %>
          <%= @booking.flight.decorate.departure_t %>
        </div>
      </div>
      <div class="col l2"> >>> </div>
      <div class="col l5">
        <h5>TO</h5>
        <div>
          <%= @booking.flight.destination_airport.decorate.name_with_state %> state
        </div>
        <div>
          <%= @booking.flight.decorate.arrival_d %>
          <%= @booking.flight.decorate.arrival_t %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col l7">---------------------------------------------------
      ----------------------------------------------></div>
      <div class="bold col l5">Booking Number: <%= @booking.booking_number %></div>
    </div>
  </div>
  <%= render partial: "bookings/passengers" %>
</div>

app/views/bookings/_flight_details.html.erb
<div class="row">
  <div class="col l5 bold">Airline</div>
  <div class="col l7"><%= @booking.flight.airline %></div>
</div>
<div class="row">
  <div class="col l5 bold">Flight Number</div>
  <div class="col l7"><%= @booking.flight.id %></div>
</div>
<div class="row">
  <div class="col l5 bold">Origin Airport</div>
  <div class="col l7">
    <div>
      <%= @booking.flight.origin_airport.decorate.name_with_state %> state
    </div>
    <div>
      <%= @booking.flight.decorate.departure_d %>
    </div>
    <div>
    <%= @booking.flight.decorate.departure_t %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col l5 bold">Destination Airport</div>
  <div class="col l7">
    <div>
      <%= @booking.flight.destination_airport.decorate.name_with_state %> state
    </div>
    <div>
      <%= @booking.flight.decorate.arrival_d %>
    </div>
    <div>
    <%= @booking.flight.decorate.arrival_t %>
    </div>
  </div>
</div>

app/views/bookings/_passengers.html.erb
<h5>Passengers</h5>
<div class="">
  <table class="table">
    <thead>
      <tr><th>SN</th><th>Name</th><th>Email</th><th>Phone</th></tr>
    </thead>
    <tbody>
      <% @booking.passengers.each_with_index do |p, index| %>
        <tr>
          <td><%= (index + 1).to_s + "> " %></td>
          <td><%= p.name %></td>
          <td><%= p.email %></td>
          <td><%= p.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/book.html.erb
<div class="container body">
  <div class="row booking">
    <%= form_for @booking do |f| %>
    <%= f.hidden_field :flight_id %>
      <div class="col l8" id="passengers">
        <h5>Passengers Details</h5>
        <% if current_user.nil? %>
          <p>
            <strong>As you are not logged in, note the following:</strong><br>
            1. The book confirmation mail will be sent to the first passenger email you enter here.
          </p>
        <% end %>
        <%= f.fields_for :passengers do |p| %>
          <div class="passenger-div">
            <div>
              <%= p.hidden_field :id %>
              <%= p.text_field :name, placeholder: "Passenger Name", required: "required" %>
            </div>
            <div class="row">
              <div class="col l6">
                <%= p.email_field :email, placeholder: "Email Address", required: "required" %>
              </div>
              <div class="col l6">
                <%= p.telephone_field :phone, placeholder: "Phone Number" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col l4">
        <h5>Flight Details</h5>
        
        <%= render "flight_details" %>

        <div class="row">
          <div class="col l5 bold">Flight Price</div>
          <div class="col l7">NGN <%= @booking.flight.price %> / passenger</div>
        </div>
        <div class="row">
          <div class="col l5 bold"></div>
          <div class="col l7">
            <% if @booking.new_record? %>
              <%= f.submit "Proceed to Checkout", class: "btn" %>
            <% else %>
              <%= f.submit "Update", class: "btn" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/checkout.html.erb
<div class="container body">
  <div class="row booking">
    
    <div class="col l8" id="passengers">
      <%= render "passengers" %>
    </div>
    
    <div class="col l4">
      <h5>Flight Details</h5>
      
      <%= render "flight_details" %>

      <div class="row">
        <div class="col l5 bold">Booking Number</div>
        <div class="col l7">
          <%= @booking.booking_number %>
        </div>
      </div>

      <h5>Payment</h5>
      
      <div class="row">
        <div class="col l5 bold">Total Amount</div>
        <div class="col l7">NGN <%= @booking.flight.price * @booking.passengers.count %> </div>
      </div>
      <div class="row">
        <div class="col l5 bold"></div>
        <div class="col l7">
          <%= link_to "Make Payment", paypal_url(@booking, payment_bookings_url(@booking.id)), class: "btn" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/bookings/confirmation.html.erb
<div class="container body">
  <div class="row booking">
    <div class="col l8">
      <%= render "content" %>
    </div>
    <div class="col l4" id="passengers">
      <h5>Thank You</h5>
      
      <div class="row">
        <div class="col l12">Your booking and payment was successful. A copy this confirmation page was sent to your email address. Please take note of your "Booking Number", for you will need it to manage this booking. It is also in the mail sent to you.</div>
      </div>
      <div class="row">
        <div class="col l5 bold">
          <%= link_to "Close", "#", class: "btn grey" %>
        </div>
        <div class="col l7">
          <%= link_to "Print", "#", class: "btn" %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container body">
  <div class="booking">
    <% if @bookings.blank? %>
      <p>You have not booked any flight with us. :D</p>
    <% else %>
      <table class="bordered">
        <thead>
          <tr>
            <th>Book Number</th>
            <th>Airline</th>
            <th>Origin</th>
            <th>Destination</th>
            <th>Passengers</th>
            <th>Manage</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td>
                <%= booking.booking_number %>
              </td>
              <td>
                <%= booking.flight.airline %>
              </td>
              <td>
                <div>
                  <%= booking.flight.origin_airport.decorate.name_with_state %>
                </div>
                <div>
                  <%= booking.flight.departure_datetime %>
                </div>
              </td>
              <td>
                <div>
                  <%= booking.flight.destination_airport.decorate.name_with_state %>
                </div>
                <div>
                  <%= booking.flight.arrival_datetime %>
                </div>
              </td>
              <td>
                <%= booking.passengers.size %>
              </td>
              <td>
                <div>
                  <% if booking.flight.departure_datetime > Time.now %>
                    <span><%= link_to "Update", edit_booking_path(booking.id) %></span> |
                    <span><%= link_to "Cancel", booking_path(booking.id), method: :delete %></span>
                  <% else %>
                    <span>departed</span>
                  <% end %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/bookings/manage.html.erb
<div class="container body manage">
  <h5>
    Enter your booking Number
  </h5>
  <div>
    <%= form_tag search_bookings_path, method: :get do %>
      <%= number_field_tag :booking_number %>
      <%= submit_tag "Search", class: "btn" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row booking">
    <%= form_for @booking do |f| %>
    <%= f.hidden_field :flight_id %>
      <div class="col l8" id="passengers">
        <h5>Passengers Details</h5>
        <%= f.fields_for :passengers do |p| %>
          <div class="passenger-div">
            <div>
              <%= p.text_field :name, placeholder: "Passenger Name", required: "required" %>
            </div>
            <div class="row">
              <div class="col l6">
                <%= p.email_field :email, placeholder: "Email Address" %>
              </div>
              <div class="col l6">
                <%= p.telephone_field :phone, placeholder: "Phone Number" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col l4">
        <h5>Flight Details</h5>
        <div class="row">
          <div class="col l5 bold">Airline</div>
          <div class="col l7"><%= @flight.airline %></div>
        </div>
        <div class="row">
          <div class="col l5 bold">Flight Number</div>
          <div class="col l7"><%= @flight.id %></div>
        </div>
        <div class="row">
          <div class="col l5 bold">Origin Airport</div>
          <div class="col l7">
            <div>
              <%= @flight.origin_airport.name + ", " + @flight.origin_airport.state %> state
            </div>
            <div>
              <% d_date = Date.parse(@flight.departure_datetime.to_s) %>
              <%= d_date.strftime("%A, #{d_date.day.ordinalize} %b %Y") %>
            </div>
            <div>
              <% d_time = Time.parse(@flight.departure_datetime.to_s) %>
              <%= d_time.strftime("%l:%M %P") %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col l5 bold">Destination Airport</div>
          <div class="col l7">
            <div>
              <%= @flight.destination_airport.name + ", " + @flight.destination_airport.state %> state
            </div>
            <div>
              <% a_date = Date.parse(@flight.arrival_datetime.to_s) %>
              <%= a_date.strftime("%A, #{a_date.day.ordinalize} %b %Y") %>
            </div>
            <div>
              <% a_time = Time.parse(@flight.arrival_datetime.to_s) %>
              <%= a_time.strftime("%l:%M %P") %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col l5 bold">Flight Price</div>
          <div class="col l7">NGN <%= @flight.price %> / passenger</div>
        </div>
        <div class="row">
          <div class="col l5 bold"></div>
          <div class="col l7">
            <%= f.submit "Proceed to Checkout", class: "btn" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>