config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users, only: [:create]
  resources :sessions, only: [:create]

  resources :flights, only: [:index] do
    collection do
      get :search
      get "/:flight_id/booking/seats/:seats" => "bookings#book", as: :book
    end
  end

  resources :bookings, only: [:create, :index, :edit, :update, :destroy] do
    collection do
      get :manage
      get :search
      get "/:booking_id/checkout" => "bookings#checkout", as: :checkout
      get "/:booking_id/payment" => "bookings#payment", as: :payment
      get "/:booking_id/confirmation" => "bookings#confirmation",
          as: :confirmation
    end
  end

end

app/views/pages/_search_form.html.erb
<div class="row">
  <%= form_for @presenter.flight, url: search_flights_path, remote: true, method: :get do |f|%>
    <div class="col l4">
      <%= f.select :origin_airport_id, list_airports, { prompt: "Select Origin Airport", include_blank: "All"}, { required: "required", class: "home-input browser-default" } %>
    </div>
    <div class="col l4">
      <%= f.select :destination_airport_id, list_airports, { prompt: "Select Destination Airport", include_blank: "All"}, { required: "required", class: "home-input browser-default" } %>
    </div>
    <div class="col l2">
      <%= f.date_field :departure_datetime, { class: "datepicker home-input", placeholder: "Travel Date" } %>
    </div>
    <div class="col l1">
      <%= f.number_field :available_seats, { value: 1, placeholder: "Number of Travelers", class: "home-input", required: "required", min: 1 } %>
    </div>
    <div class="col l1">
      <%= f.button class: "btn"  do %>
        <i class="material-icons up-left-rotate">send</i>
      <% end %>
      
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="home-body">
  <div class="container">
    <div class="search-form-section">
      <%= render "search_form" %>
    </div>
  </div>
  <div class="container">
    <div class="flight-board">
      <h5>Flight Time Board</h5>
      <div id="flight-time-board">
        <%= render @presenter.flight %>
      </div>
    </div>
  </div>
</div>