config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  resources :users, only: [:create]
  resources :sessions, only: [:create]

  resources :flights, only: [:index] do
    collection do
      get :search
      get "/:flight_id/booking/seats/:seats" => "bookings#book", as: :book
    end
  end

  resources :bookings, only: [:create, :index, :edit, :update, :destroy] do
    collection do
      get :manage
      get :search
      get "/:booking_id/checkout" => "bookings#checkout", as: :checkout
      get "/:booking_id/payment" => "bookings#payment", as: :payment
      get "/:booking_id/confirmation" => "bookings#confirmation",
          as: :confirmation
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to(
      login_url,
      alert: "Login to perform this action"
    ) if current_user.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="page-footer grey darken-4">
  <div class="container">
    <div class="row">
      <div class="col l8 s6">
        <h5 class="white-text">Let's fly -</h5>
        <p class="grey-text text-lighten-4">...is an online flight booking service. We are partnered with 2768 nigerian airlines and all the 402 airports across the country. We get real time information from the immigration office. The security bodies in Nigeria are our source of confidence. We have got you covered man... Nothing more to worry.</p>
      </div>
      <div class="col l3 offset-l1 s6">
        <h5 class="white-text">Our Social</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/science2">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="https://twitter.com/EmmanuelScience">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="https://plus.google.com/109595750984826808317/posts/p/pub">Google+</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Pinterest</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright black">
    <div class="container">
    © 2015 Copyright - <a href="http://andela.com">Andela</a>
    <a class="grey-text text-lighten-4 right" href="https://github.com/andela-echigbo/">EmmanuelScience</a>
    </div>
  </div>
</footer>
    

app/views/application/_header.html.erb
<div class="navbar-fixed">
  <nav class="teal darken-3">
    <div class="container">
      <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo">Let's fly</a>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down top-nav">
          <li><a href="<%= flights_path %>">All Flight</a></li>
          <li><a href="<%= manage_bookings_path %>">Manage Bookings</a></li>
          <% if current_user %>
            <li>
              <a class="dropdown-button" href="#!" data-activates="dropdown1">
                <%= current_user.name %><i class="material-icons right">arrow_drop_down</i>
              </a>

              <ul id="dropdown1" class="dropdown-content">
                <li><a href="<%= bookings_url %>" class="">My Bookings</a></li>
                <li class="divider"></li>
                <li><a href="<%= logout_url %>" class="">logout</a></li>
              </ul>
            </li>
          <% else %>
            <li class="no-hover"><a href="<%= login_url %>" class="btn auth-btn">signin</a></li>
            <li class="no-hover"><a href="<%= signup_url %>" class="btn auth-btn">signup</a></li>
            <!-- <li><a href="mobile.html">Mobile</a></li> -->
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <li><a href="<%= flights_path %>">All flight</a></li>
          <li><a href="<%= manage_bookings_path %>">Manage bookings</a></li>
          <% if current_user %>
            <li><a href="<%= login_url %>" class="">Past Booking</a></li>
            <li><a href="<%= "#" %>" class=""><%= current_user.name %></a></li>
            <li><a href="<%= logout_url %>" class="">logout</a></li>
          <% else %>
            <li><a href="<%= login_url %>">signin</a></li>
            <li><a href="<%= signup_url %>">signup</a></li>
            <!-- <li><a href="mobile.html">Mobile</a></li> -->
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>
<div>
  <% unless flash['notice'].nil? %>
    <script type="text/javascript">
      Materialize.toast("<span><%= flash['notice'] %></span>", 5000);
    </script>
  <% end %>
  <% unless flash['alert'].nil? %>
    <script type="text/javascript">
      Materialize.toast("<span><%= flash['alert'] %></span>", 5000);
    </script>
  <% end %>
<end>